name: crowd
description: "Explore USM library with TaraLibrary mobile app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile/profile.png
    - assets/images/profile/avatar.jfif
    - assets/images/section/reference.jpg
    - assets/images/section/medical.jpg
    - assets/images/section/serials.jpg
    - assets/images/section/publication.jpg
    - assets/images/icons/facebook.png
    - assets/images/icons/email.png

  fonts:
    - family: Geist
      fonts:
        - asset: fonts/Geist-Regular.ttf
        - asset: fonts/Geist-Black.ttf
        - asset: fonts/Geist-Light.ttf
        - asset: fonts/Geist-Bold.ttf
        - asset: fonts/Geist-Medium.ttf
        - asset: fonts/Geist-SemiBold.ttf
        - asset: fonts/Geist-Thin.ttf
        - asset: fonts/Geist-UltraBlack.ttf
        - asset: fonts/Geist-UltraLight.ttf

